server:
  port: 9000

spring:
  application:
    name: zuul-demo

eureka:
  client:
    service-url:
      # 配置当前微服务作为Eureka客户端访问Eureka服务器端时使用的地址
      defaultZone: http://localhost:5000/eureka/

zuul:
  routes:
    # 自定义路由规则的名称，在底层的数据结构中是Map的键
    consumer-demo:
      # 目标微服务的名称，ZuulRoute类型的一个属性
      service-id: consumer-demo
      # 用来代替目标微服务名称的路径，ZuulRoute类型的一个属性，/**表示匹配多层路径，如果没有加/**则不能匹配后续的多层路径了
      path: /zuul-consumer/**

  # 忽略指定微服务名称，让用户不能通过微服务名称访问，'*'
  #  ignored-services:
  #    - consumer-demo
  # 忽略所有微服务名称
  ignored-services: '*'

  # 给访问路径添加统一前缀
  #  prefix: /test
